// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SparsePatterns {
    #[prost(string, repeated, tag = "1")]
    pub prefixes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TreeState {
    #[deprecated]
    #[prost(bytes = "vec", tag = "1")]
    pub legacy_tree_id: ::prost::alloc::vec::Vec<u8>,
    /// Alternating positive and negative terms if there's a conflict, otherwise a
    /// single (positive) value
    #[prost(bytes = "vec", repeated, tag = "5")]
    pub tree_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Labels for the terms of a conflict.
    #[prost(string, repeated, tag = "7")]
    pub conflict_labels: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "3")]
    pub sparse_patterns: ::core::option::Option<SparsePatterns>,
    /// Legacy Watchman-only cursor. Read for migration, but new state is written
    /// to fsmonitor_cursor instead.
    #[deprecated]
    #[prost(message, optional, tag = "4")]
    pub watchman_clock: ::core::option::Option<WatchmanClock>,
    #[prost(message, optional, tag = "8")]
    pub fsmonitor_cursor: ::core::option::Option<FsmonitorCursor>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WatchmanClock {
    #[prost(oneof = "watchman_clock::WatchmanClock", tags = "1, 2")]
    pub watchman_clock: ::core::option::Option<watchman_clock::WatchmanClock>,
}
/// Nested message and enum types in `WatchmanClock`.
pub mod watchman_clock {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum WatchmanClock {
        #[prost(string, tag = "1")]
        StringClock(::prost::alloc::string::String),
        #[prost(int64, tag = "2")]
        UnixTimestamp(i64),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FsmonitorCursor {
    #[prost(oneof = "fsmonitor_cursor::Cursor", tags = "1")]
    pub cursor: ::core::option::Option<fsmonitor_cursor::Cursor>,
}
/// Nested message and enum types in `FsmonitorCursor`.
pub mod fsmonitor_cursor {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Cursor {
        #[prost(message, tag = "1")]
        Watchman(super::WatchmanClock),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Checkout {
    /// The operation at which the working copy was updated.
    #[prost(bytes = "vec", tag = "2")]
    pub operation_id: ::prost::alloc::vec::Vec<u8>,
    /// An identifier for this workspace. It is used for looking up the current
    /// working-copy commit in the repo view. Currently a human-readable name.
    /// TODO: Is it better to make this a UUID and a have map that to a name in
    /// config? That way users can rename a workspace.
    #[prost(string, tag = "3")]
    pub workspace_name: ::prost::alloc::string::String,
}
/// Compact durable state for a local working copy. This replaces the legacy
/// split checkout/tree_state files. It intentionally contains no per-path file
/// state: the semantic tree is paired with an optional authoritative filesystem
/// baseline instead.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkingCopyState {
    #[prost(uint32, tag = "1")]
    pub format_version: u32,
    /// The operation at which the working copy was updated.
    #[prost(bytes = "vec", tag = "2")]
    pub operation_id: ::prost::alloc::vec::Vec<u8>,
    /// The workspace name used to look up the working-copy commit in the view.
    #[prost(string, tag = "3")]
    pub workspace_name: ::prost::alloc::string::String,
    /// Alternating positive and negative terms if there's a conflict, otherwise a
    /// single positive value.
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub tree_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, repeated, tag = "5")]
    pub conflict_labels: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "6")]
    pub sparse_patterns: ::core::option::Option<SparsePatterns>,
    /// Present only for Watchman-style mutable-filesystem monitors. AWACS
    /// baselines are typed snapshot state below, not event-stream cursors.
    #[prost(message, optional, tag = "7")]
    pub fsmonitor_cursor: ::core::option::Option<FsmonitorCursor>,
    #[prost(uint64, tag = "8")]
    pub generation: u64,
    #[prost(enumeration = "WorkingCopyStatePhase", tag = "9")]
    pub phase: i32,
    /// The intended semantic tree during an interrupted materialization. These
    /// are populated only for PendingMaterialization.
    #[prost(bytes = "vec", repeated, tag = "10")]
    pub pending_tree_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, repeated, tag = "11")]
    pub pending_conflict_labels: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    /// Exact AWACS snapshot paired with the semantic tree for CleanBaseline.
    /// This is absent for NoBaseline and ordinary mutable-filesystem scans.
    #[prost(message, optional, tag = "12")]
    pub baseline: ::core::option::Option<AwacsSnapshotBaseline>,
    /// Candidate retained snapshot while a baseline promotion is in flight.
    #[prost(message, optional, tag = "13")]
    pub pending_baseline: ::core::option::Option<AwacsSnapshotBaseline>,
    #[prost(bytes = "vec", tag = "14")]
    pub transition_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "15")]
    pub no_baseline_reason: ::prost::alloc::string::String,
    #[prost(string, tag = "16")]
    pub mutation_kind: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "17")]
    pub pending_sparse_patterns: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AwacsSnapshotBaseline {
    /// Identity of the exact immutable Btrfs snapshot paired with the tree.
    #[prost(bytes = "vec", tag = "1")]
    pub filesystem_uuid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub subvolume_uuid: ::prost::alloc::vec::Vec<u8>,
    /// Authenticated AWACS capability proving continuity from this snapshot.
    #[prost(bytes = "vec", tag = "3")]
    pub continuity_token: ::prost::alloc::vec::Vec<u8>,
    /// Non-empty only once AWACS exposes a durable client-owned retention pin.
    #[prost(bytes = "vec", tag = "4")]
    pub retention_token: ::prost::alloc::vec::Vec<u8>,
    /// JJ-owned inputs which affect interpretation of the snapshot contents.
    #[prost(bytes = "vec", tag = "5")]
    pub interpretation_input_fingerprint: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WorkingCopyStatePhase {
    NoBaseline = 0,
    CleanBaseline = 1,
    PendingMaterialization = 2,
    PendingBaselineCommit = 3,
}
impl WorkingCopyStatePhase {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NoBaseline => "NoBaseline",
            Self::CleanBaseline => "CleanBaseline",
            Self::PendingMaterialization => "PendingMaterialization",
            Self::PendingBaselineCommit => "PendingBaselineCommit",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NoBaseline" => Some(Self::NoBaseline),
            "CleanBaseline" => Some(Self::CleanBaseline),
            "PendingMaterialization" => Some(Self::PendingMaterialization),
            "PendingBaselineCommit" => Some(Self::PendingBaselineCommit),
            _ => None,
        }
    }
}
